[package]
name = "stwo-polynomial"
version = "0.1.0"
edition = "2021"
description = "A cryptographic library providing prove and verify functionality"
license = "MIT OR Apache-2.0"
repository = "https://github.com/example/stwo-polynomial"
authors = ["Your Name <you@example.com>"]

[lib]
name = "stwo_polynomial"
path = "src/lib.rs"

[[example]]
name = "prove_fibonacci"
path = "examples/prove_fibonacci/prove.rs"

[[example]]
name = "verify_fibonacci"
path = "examples/verify_fibonacci/verify.rs"

[[example]]
name = "privacy_pools"
path = "examples/privacy_pools/main.rs"

[[example]]
name = "fibonacci_onchain"
path = "examples/fibonacci_onchain/main.rs"

[[example]]
name = "fibonacci_blake"
path = "examples/fibonacci_blake/src/main.rs"

[dependencies]
stwo = { git = "https://github.com/piotr-stec/stwo-fork-keccak", features = ["prover"], branch = "channel/solidity" }
std-shims = { git = "https://github.com/piotr-stec/stwo-fork-keccak", features = ["std"],branch = "channel/solidity"  }
stwo-constraint-framework = { git = "https://github.com/piotr-stec/stwo-fork-keccak", features = ["prover", "std"], branch = "channel/solidity" }
num-traits = "0.2"
thiserror = { version = "2.0.12", default-features = false }
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3.18", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
alloy = { version = "0.8", features = ["full", "node-bindings", "rpc-types", "sol-types"] }
tokio = { version = "1.0", features = ["full"] }
itertools = "0.13"