[package]
name = "stwo-polynomial"
version = "0.1.0"
edition = "2021"
description = "A cryptographic library providing prove and verify functionality"
license = "MIT OR Apache-2.0"
repository = "https://github.com/example/stwo-polynomial"

# [lib]
# name = "stwo_polynomial"
# path = "src/lib.rs"

# [[example]]
# name = "prove_fibonacci"
# path = "examples/prove_fibonacci/prove.rs"

# [[example]]
# name = "verify_fibonacci"
# path = "examples/verify_fibonacci/verify.rs"

# [[example]]
# name = "privacy_pools"
# path = "examples/privacy_pools/main.rs"

# [[example]]
# name = "fibonacci_onchain"
# path = "examples/fibonacci_onchain/main.rs"

[dependencies]
stwo-prover = { git = "https://github.com/piotr-stec/stwo-fork-keccak", branch = "feat/gnark" }
